codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1.5%
    patch: no
    changes: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - tests
  - docs/conf.py
