name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          enable-cache: true

      - run: uv build
      - run: uv publish --token ${{ secrets.PYPI_TOKEN }}
